version: '3.9'

services:
  eventzen.api:
    image: ${DOCKER_REGISTRY-}eventzenapi
    container_name: EventZen.Api
    build:
      context: .
      dockerfile: src/API/EventZen.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - eventzen.database
  eventzen.database:
    image: postgres:latest
    container_name: EventZen.Database
    environment:
      - POSTGRES_DB=eventzen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5433:5432

